
DELETE http://127.0.0.1:3000/api/vendor/products/delete/5faa2a8e789d0223d831bad5 HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE2ODM0ZjMxYjk3OTcxZjgyNmNkYzQiLCJpYXQiOjE2MDQ3NjE3MDF9.92HVBf0qo6pRGQNqaVdDn6DrNiXrfEfgPuvTGDVSN58


### update a product details as a vendor
PATCH  http://127.0.0.1:3000/api/vendor/products/update/5fa94df71a3b532fe4533d022 HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE2ODM0ZjMxYjk3OTcxZjgyNmNkYzQiLCJpYXQiOjE2MDQ3NjE3MDF9.92HVBf0qo6pRGQNqaVdDn6DrNiXrfEfgPuvTGDVSN58
Content-Type: application/json

{
    "product_name": "Pizza 3.0"
}

### display products of the current vendor
GET http://127.0.0.1:3000/api/vendor/products HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFlNzZmYjFmMzhkNzE1Zjg5MWE0MjEiLCJpYXQiOjE2MDY0MDU0NDN9.Js9jxbRYYAJ9ZDNLXZ7S0ndDPfoTOrT3yAWx2jZIROA

### 5fa811d2232e0d015855962a : user id
### user register
POST http://127.0.0.1:3000/api/register HTTP/1.1
Content-Type: application/json

{
    "name": "Update Test",
    "email": "update@gmail.com",
    "password": "12345678",
    "role": "user",
    "pincode": "673601"
}

### user login
POST http://127.0.0.1:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "nihalninu25@gmail.com",
    "password": "12345678"
}
### user details update
PATCH  http://127.0.0.1:3000/api/update HTTP/1.1
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmNjYTU5OTllZmY1YzE1ZTg5YWRiYmQiLCJpYXQiOjE2MDcyNDc5MjV9.B9BN-jI_eiL5-kYYQaiORYJhMxtmVuu87WSZ9sJSmug

{
    "email": "testinggg@gmail.com",
    "password": "12345678",
    "role": null
}

### auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4MTFkMjIzMmUwZDAxNTg1NTk2MmEiLCJpYXQiOjE2MDQ4NTAyMTZ9.uRvGVl6l9au8VRQqTDETpe1kkBqL3IM3lyxK7yiIemg
### get product list based on pincode

GET http://127.0.0.1:3000/api/home?pincode=673601&category=Food HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE2ODM0ZjMxYjk3OTcxZjgyNmNkYzQiLCJpYXQiOjE2MDQ3NjE3MDF9.92HVBf0qo6pRGQNqaVdDn6DrNiXrfEfgPuvTGDVSN58

### Vendor List

GET http://127.0.0.1:3000/api/admin/vendor/list HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4MTFkMjIzMmUwZDAxNTg1NTk2MmEiLCJpYXQiOjE2MDUyNjgwNzJ9.QSn5nmmyS7O-EsptzYOBtCYkZWKdvvvRCs4aUMAtXtI

### Add vendor as an "Admin"

POST http://127.0.0.1:3000/api/admin/vendor/add HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4MTFkMjIzMmUwZDAxNTg1NTk2MmEiLCJpYXQiOjE2MDUyNjgwNzJ9.QSn5nmmyS7O-EsptzYOBtCYkZWKdvvvRCs4aUMAtXtI
Content-Type: application/json

{
    "name": "Test Vendor 2",
    "email": "vendortest2@gmail.com",
    "password": "n2ks9x64",
    "role": "vendor",
    "pincode": "673601"
}
###
DELETE http://127.0.0.1:3000/api/admin/vendor/delete/vendortestt@gmail.com HTTP/1.1
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4MTFkMjIzMmUwZDAxNTg1NTk2MmEiLCJpYXQiOjE2MDUyNjgwNzJ9.QSn5nmmyS7O-EsptzYOBtCYkZWKdvvvRCs4aUMAtXtI
###

PATCH  http://127.0.0.1:3000/api/admin/vendor/update/vendortest@gmail.com HTTP/1.1
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4MTFkMjIzMmUwZDAxNTg1NTk2MmEiLCJpYXQiOjE2MDUyNjgwNzJ9.QSn5nmmyS7O-EsptzYOBtCYkZWKdvvvRCs4aUMAtXtI

{
    "name": "Test Vendor 1",
    "email": null
}
### Category function testing
###Adding Category

POST http://127.0.0.1:3000/api/vendor/add-category HTTP/1.1
Content-Type: application/json

{
    "category":"new category"
}

###adding product with category value checked with category document in mongodb

GET http://127.0.0.1:3000/test/2?q=Office%20Items HTTP/1.1

###deleting category

GET http://127.0.0.1:3000/test/3?q=test HTTP/1.1

###image upload test

POST http://127.0.0.1:3000/test/3?q=test HTTP/1.1

###List Category Items
GET http://127.0.0.1:3000/api/vendor/category HTTP/1.1

### Search Functionality
GET http://127.0.0.1:3000/api/home/items?search=h&pincode=673601

### Payment
POST http://127.0.0.1:3000/api/razorpay/payment HTTP/1.1
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFlNzZmYjFmMzhkNzE1Zjg5MWE0MjEiLCJpYXQiOjE2MDgxMTc2MzF9.Prr_wdNYz8pTu5PdUYS-2xYlyLkalHR0DyBZys3167U

{
    "amount":100,
    "currency":"INR"
}
### Add Order details to database
POST http://127.0.0.1:3000/api/razorpay/order/add HTTP/1.1
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFlNzZmYjFmMzhkNzE1Zjg5MWE0MjEiLCJpYXQiOjE2MDgxMTc2MzF9.Prr_wdNYz8pTu5PdUYS-2xYlyLkalHR0DyBZys3167U

{
    "vendor_id_list": [
        "5fae76fb1f38d715f891a421",
        "5fac12d327b1cf34bcffbafc"
    ],
    "products":[
        "test product 1",
        "test product 2"
    ],
    "address": "test address"
}

###patch
PATCH  http://127.0.0.1:3000/api/razorpay/order/update HTTP/1.1
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFlNzZmYjFmMzhkNzE1Zjg5MWE0MjEiLCJpYXQiOjE2MDgxMTc2MzF9.Prr_wdNYz8pTu5PdUYS-2xYlyLkalHR0DyBZys3167U

{
    "order_id": "order_GDmpimIrP1KqEj",
    "order_status": "test address"
}

###inserting order date to database
POST http://127.0.0.1:3000/add/date HTTP/1.1
Content-Type: application/json

{
    "customer":"test",
    "vendor_list":["test"],
    "address":"test",
    "amount":999,
    "payment_status":"test",
    "items":["test"],
    "order_id":"test"
}

###get order details for admin
GET http://127.0.0.1:3000/api/admin/order/history HTTP/1.1

### FCM setting token
POST http://127.0.0.1:3000/api/firebase/setToken HTTP/1.1
Content-Type: application/json

{
    "firebase_device_token":"dizB6iLsTyuLGZms-axIHS:APA91bGx-vzoJ983HrCdHwiQbwrsPIUgstHbXDT83GVUawcd3W4yOUb5IGDI6EvivtBEyKH6ql3KaIsKKr5oDLEMyRWt7e625lljLSCoqMRma3R7ne8o7XIFXyVGl7zpH4qZP53pDt6a"
}

### FCM setting userIid
PATCH http://127.0.0.1:3000/api/firebase/setUserId?token=dizB6iLsTyuLGZms-axIHS:APA91bGx-vzoJ983HrCdHwiQbwrsPIUgstHbXDT83GVUawcd3W4yOUb5IGDI6EvivtBEyKH6ql3KaIsKKr5oDLEMyRWt7e625lljLSCoqMRma3R7ne8o7XIFXyVGl7zpH4qZP53pDt6a HTTP/1.1
Content-Type: application/json

{
    "user_id":"TESTING"
}

### Send Notifications
POST http://127.0.0.1:3000/api/firebase/send HTTP/1.1
Content-Type: application/json

{
    "notification": {
        "title": "From Admin",
        "body": "To all vendors"
    },
    "target": "vendors"
}

### Get Notifications for vendors
GET http://127.0.0.1:3000/api/vendor/notification HTTP/1.1
Content-Type: application/json

{
    "user_id": "5fae76fb1f38d715f891a421"
}